sonar.projectKey=AndresVeraCachoo_sistemas-distribuidos
sonar.organization=andresveracachoo
sonar.host.url=https://sonarcloud.io

sonar.sources=webapp/src/main, pokemon-api/src
sonar.tests=webapp/src/test, pokemon-api/test
sonar.java.binaries=webapp/target/classes

sonar.exclusions=webapp/target/**, pokemon-api/env/**, pokemon-api/__pycache__/**, **/*.css, **/*.js

sonar.python.version=3.13

# COVERAGE
sonar.python.coverage.reportPaths=pokemon-api/coverage.xml
sonar.coverage.jacoco.xmlReportPaths=webapp/target/site/jacoco/jacoco.xml