# Claves que te ha dado SonarCloud
sonar.projectKey=AndresVeraCachoo_sistemas-distribuidos
sonar.organization=andresveracachoo
sonar.host.url=https://sonarcloud.io

sonar.sources=frontend/src/main, backend/src

sonar.tests=frontend/src/test, backend/test

sonar.java.binaries=frontend/target/classes

sonar.exclusions=frontend/target/**, backend/env/**, backend/__pycache__/**, **/*.css, **/*.js

sonar.python.version=3.13