# Claves que te ha dado SonarCloud
sonar.projectKey=AndresVeraCachoo_sistemas-distribuidos
sonar.organization=andresveracachoo

# Apuntamos a la nube
sonar.host.url=https://sonarcloud.io

# Le decimos dónde está el código
sonar.sources=frontend/src/main, backend/src
# Marcamos que version de python uso para un analisis mas preciso:
sonar.python.version=3.13