server.port=8081
spring.application.name=frontend

# Si no encuentra las variables de Docker, usará localhost y el puerto 5433 que pusimos antes
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/practica_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin_secreto}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Para que Thymeleaf se actualice al instante si cambias un HTML sin reiniciar el servidor
spring.thymeleaf.cache=false

# Si no está en Docker, buscará el backend de Python en localhost
api.python.url=${API_PYTHON_URL:http://localhost:5000}

# Credenciales por defecto (Extraídas para seguridad)
app.admin.password=pueblopaleta